app: test-app
env: staging
namespace: staging
deploy:
  branch: main
  event: push
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.38.0
values:
  containerPort: 9000
  gitRepository: gimlet-io/test-app
  gitSha: '{{ .SHA }}'
  image:
    repository: ghcr.io/gimlet-io/test-app
    tag: '{{ .SHA }}'
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx
    host: test-app.staging.turbopizza.net
    tlsEnabled: true
  replicas: 2
  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 40m
      memory: 10Mi
  vars:
    MY_NEW_DUMMY_VAR: my-new-dummy-value-fixed
strategicMergePatches: ""
json6902Patches: []
manifests: ""
